cd /d "%~dp0"
del        "InternetMouseFor7\MainWindow.xaml"
mklink     "InternetMouseFor7\MainWindow.xaml" "%~dp0InternetMouseFor10\MainWindow.xaml"
del        "InternetMouseFor8\MainWindow.xaml"
mklink     "InternetMouseFor8\MainWindow.xaml" "%~dp0InternetMouseFor10\MainWindow.xaml"
del        "InternetMouseFor7\MainWindow.xaml.cs"
mklink     "InternetMouseFor7\MainWindow.xaml.cs" "%~dp0InternetMouseFor10\MainWindow.xaml.cs"
del        "InternetMouseFor8\MainWindow.xaml.cs"
mklink     "InternetMouseFor8\MainWindow.xaml.cs" "%~dp0InternetMouseFor10\MainWindow.xaml.cs"
del        "InternetMouseFor7\app.manifest"
mklink     "InternetMouseFor7\app.manifest"    "%~dp0InternetMouseFor10\app.manifest"
del        "InternetMouseFor8\app.manifest"
mklink     "InternetMouseFor8\app.manifest"    "%~dp0InternetMouseFor10\app.manifest"
del        "InternetMouseFor7\Model\BeanCreateQueue.cs"
mklink     "InternetMouseFor7\Model\BeanCreateQueue.cs"  "%~dp0InternetMouseFor10\Model\BeanCreateQueue.cs"
del        "InternetMouseFor8\Model\BeanCreateQueue.cs"
mklink     "InternetMouseFor8\Model\BeanCreateQueue.cs"  "%~dp0InternetMouseFor10\Model\BeanCreateQueue.cs"
del        "InternetMouseFor7\Model\KEYEVENTF.cs"
mklink     "InternetMouseFor7\Model\KEYEVENTF.cs"        "%~dp0InternetMouseFor10\Model\KEYEVENTF.cs"
del        "InternetMouseFor8\Model\KEYEVENTF.cs"
mklink     "InternetMouseFor8\Model\KEYEVENTF.cs"        "%~dp0InternetMouseFor10\Model\KEYEVENTF.cs"
rem del    "InternetMouseFor7\Model\ModelAws.cs"
rem mklink "InternetMouseFor7\Model\ModelAws.cs"         "%~dp0InternetMouseFor10\Model\ModelAws.cs"
del        "InternetMouseFor8\Model\ModelAws.cs"
mklink     "InternetMouseFor8\Model\ModelAws.cs"         "%~dp0InternetMouseFor10\Model\ModelAws.cs"
del        "InternetMouseFor7\Model\ModelInput.cs"
mklink     "InternetMouseFor7\Model\ModelInput.cs"       "%~dp0InternetMouseFor10\Model\ModelInput.cs"
del        "InternetMouseFor8\Model\ModelInput.cs"
mklink     "InternetMouseFor8\Model\ModelInput.cs"       "%~dp0InternetMouseFor10\Model\ModelInput.cs"
del        "InternetMouseFor7\Model\ModelInputKey.cs"
mklink     "InternetMouseFor7\Model\ModelInputKey.cs"    "%~dp0InternetMouseFor10\Model\ModelInputKey.cs"
del        "InternetMouseFor8\Model\ModelInputKey.cs"
mklink     "InternetMouseFor8\Model\ModelInputKey.cs"    "%~dp0InternetMouseFor10\Model\ModelInputKey.cs"
del        "InternetMouseFor7\Model\ModelInputMouse.cs"
mklink     "InternetMouseFor7\Model\ModelInputMouse.cs"  "%~dp0InternetMouseFor10\Model\ModelInputMouse.cs"
del        "InternetMouseFor8\Model\ModelInputMouse.cs"
mklink     "InternetMouseFor8\Model\ModelInputMouse.cs"  "%~dp0InternetMouseFor10\Model\ModelInputMouse.cs"

pause
